apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          thrift_compact:
    processors:

    exporters:
      logging:
        loglevel: info
      otlp:
        endpoint: otel-collector-opentelemetry-collector.otel.svc.cluster.local:4317
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [otlp]