apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "ca-issuer"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"    
  name: jaeger-hotrod
spec:
  rules:
  - host: jaeger-hotrod.local.dev
    http:
      paths:
      - backend:
          service:
            name: jaeger-hotrod
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - jaeger-hotrod.local.dev
    secretName: jaeger-hotrod-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: jaeger-hotrod
  name: jaeger-hotrod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: jaeger-hotrod
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jaeger-hotrod
  name: jaeger-hotrod
spec:
  containers:
  - image: jaegertracing/example-hotrod:latest
    name: jaeger-hotrod
    env:
      - name: "JAEGER_AGENT_HOST"
        value: "otel-collector-opentelemetry-collector.otel.svc.cluster.local"
      - name: "JAEGER_AGENT_PORT"
        value: "6831"
    ports:
    - containerPort: 8080